config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  apipie
  devise_for :users, ActiveAdmin::Devise.config
  namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
       mount_devise_token_auth_for 'User', at: 'auth', :controllers => { :registrations => "api/v1/users/registrations",
                                                                         sessions: "api/v1/users/sessions"}
       resources :conversations, only: [:index, :create, :destroy] do
         resources :messages, only: [:index, :create, :update, :destroy]
         get :participants
         put :add_participants
       end
       resources :staffs, only: [:show, :update, :index]
       resources :customers, only: [:show, :update]
       resources :blocked_users, only: [:index, :create, :show]
       delete 'un_blocked_user' => 'blocked_users#destroy'
       get 'eula/latest' => 'eulas#latest'
       get 'privacy/latest' => 'privacies#latest'
       resources :ratings, only: [:show, :create, :update]
       resources :reported_ratings, only: [:show, :create]
       resources :reported_chats, only: [:show, :create]
       resources :jobs
       resources :notifications, only: [:index, :destroy]
     end
   end
  ActiveAdmin.routes(self)   
  root 'admin/dashboard#index'
  resources :users
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/controllers/api/v1/notifications_controller.rb
module Api
  module V1
    class NotificationsController < ApiController
      before_action :authenticate_user!
      before_action :check_user_eula_and_privacy
      before_action :set_reported_rating, only: [:show]

      # GET /api/v1/notifications.json
      api :GET, '/notifications.json', 'Returns a list of push notifications recieved by the current user.'
      param :timestamp, String, desc: 'Timestamp of the first or last record in the cache. timestamp and direction are to be used in conjunction'
      param :direction, String, desc: 'Direction of records. up: 0 and down: 1, with up all records updated after the timestamp are returned, and with down 20 records updated before the timestamp will be returned'
      def index
        @notifications = Rpush::Client::ActiveRecord::Notification.includes(:user, :sender).where(user: current_user)
                          .where.not(device_token: nil).paginate_with_timestamp(params[:timestamp], params[:direction])
      end

      # DELETE /api/v1/notifications/1
      # DELETE /api/v1/notifications/1.json
      api :DELETE, '/notifications/:id.json', 'Delete the notification.'
      param :id, String, desc: 'Id of the job which is to be deleted.', required: true
      def destroy
        Rpush::Apns::Notification.where(id: params[:id], user: current_user).delete_all
        render json: {success: 'Notification deleted successfully.'}
      end
    end
  end
end

app/views/admin/notifications/show.html.erb
<div class="panel">
  <h3><%= @notification.try(:subject) || 'Push Notification' %></h3>
  <div class="panel-contents">
    <table style="width: 400px">
      <tr>
        <td>
          <h6>Sent By</h6>
          <%= link_to "#{@sender.full_name}(#{@sender.email})", admin_user_path(@sender) %>
        </td>
      </tr>
      <tr>
        <td>
          <h6>Sent At</h6>
          <%= @notification.created_at.strftime('%B %d, %Y %H:%M') %>
        </td>
      </tr>
      <tr>
        <td>
          <h6>Recipient</h6>
          <%= link_to "#{@recipient.username}(#{@recipient.email})", admin_user_path(@recipient) %>
        </td>
      </tr>
      <tr>
        <td><h6>Message Type</h6><%= @notification.notification_type %></td>
      </tr>
      <tr>
        <td><h6>Subject</h6><%= @notification.category %></td>
      </tr>
      <tr>
        <td><h6>Message</h6></td>
      </tr>
      <tr>
        <td><%= raw @notification.try(:message) || @notification.alert %></td>
      </tr>
    </table>
  </div>
</div>