config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  apipie
  devise_for :users, ActiveAdmin::Devise.config
  namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
       mount_devise_token_auth_for 'User', at: 'auth', :controllers => { :registrations => "api/v1/users/registrations",
                                                                         sessions: "api/v1/users/sessions"}
       resources :conversations, only: [:index, :create, :destroy] do
         resources :messages, only: [:index, :create, :update, :destroy]
         get :participants
         put :add_participants
       end
       resources :staffs, only: [:show, :update, :index]
       resources :customers, only: [:show, :update]
       resources :blocked_users, only: [:index, :create, :show]
       delete 'un_blocked_user' => 'blocked_users#destroy'
       get 'eula/latest' => 'eulas#latest'
       get 'privacy/latest' => 'privacies#latest'
       resources :ratings, only: [:show, :create, :update]
       resources :reported_ratings, only: [:show, :create]
       resources :reported_chats, only: [:show, :create]
       resources :jobs
       resources :notifications, only: [:index, :destroy]
     end
   end
  ActiveAdmin.routes(self)   
  root 'admin/dashboard#index'
  resources :users
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% if current_user && current_user.administrator? %>
        <li><%= link_to 'Admin', admin_root_path %></li>
    <% end %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/active_admin_logged_out.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>

  <% ActiveAdmin.application.stylesheets.each do |style, options| %>
    <%= stylesheet_link_tag style, options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
    <%= javascript_include_tag path %>
  <% end %>

  <%= favicon_link_tag ActiveAdmin.application.favicon if ActiveAdmin.application.favicon %>

  <% ActiveAdmin.application.meta_tags_for_logged_out_pages.each do |name, content| %>
    <%= tag(:meta, name: name, content: content) %>
  <% end %>

  <%= csrf_meta_tag %>
</head>
<body class="active_admin logged_out <%= controller.action_name %>">
<div id="wrapper">
  <div class="header" id="header">
    <h1 class="site_title" id="site_title"><%= link_to image_tag('dapper-logo.gif', style: 'height: 50px;'), 'http://dapperapps.com.au' %></h1>
    <ul class="header-item tabs" id="tabs">
      <li><%= link_to 'Home', 'http://dapperapps.com.au'%></li>
      <% if request.path != new_user_session_path %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
      <% if request.path != new_user_registration_path %>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
  <div id="content_wrapper">
    <% flash_messages.each do |type, message| %>
      <%= content_tag :div, message, class: "flash flash_#{type}" %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fram" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fram" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>